#!/usr/bin/env ruby

puts "[WARNING] 'pt2html' has been deprecated. Use 'br48' instead."
exit 1

until ARGV.empty? do
  input_file_name = ARGV.shift
  output_file_name = "#{input_file_name}.html"
  output_file_name = "#{output_file_name[0..-9]}.html" if output_file_name.end_with? ".pt.html"
  yaml_flag = false

  File.open(output_file_name, "w") do |f|
    author = date = source = url = nil
    File.open(input_file_name, "r").each_line do |line|
      line.strip!
      yaml_flag = !yaml_flag if line == "---"
      if yaml_flag && line != "---" then
        author = line[8..-1] if line.start_with? "author:"
        date = line[6..-1] if line.start_with? "date:"
        source = line[8..-1] if line.start_with? "source:"
        url = line[5..-1] if line.start_with? "url:"

      elsif !yaml_flag && line == "---" then
        line = "<a href='#{url}'>#{author} - #{source} - #{date}</a>"
        f.puts line

        line = "<blockquote>"
        f.puts line

      elsif !yaml_flag && line != "---" then
        line = "<em><strong>#{line[3..-1]}</strong></em>" if line.start_with? "___"
        line = "<strong>#{line}</strong>" if line.start_with? "__"
        line = "<em>#{line}</em>" if line.start_with? "_"

        line = "#{line}<br/>"
        f.puts line

      end
    end
    line = "</blockquote>"
    f.puts line
  end
end
