#!/usr/bin/env bash
#
# Dependencies:
# - breakdown
# - xsel

br48() {
    local filename=$1
    if [ ! -r "$filename" ]; then
        echo [ERROR] file \"$filename\" does not exist
        exit 1
    fi

    local i=0 in_yaml=false author date source url
    while read -r line; do
        if [[ $in_yaml = true ]]; then
            if [[ $line =~ ^'author: ' ]]; then
                author=${line#author: }
            elif [[ $line =~ ^'date: ' ]]; then
                date=${line#date: }
            elif [[ $line =~ ^'source: ' ]]; then
                source=${line#source: }
            elif [[ $line =~ ^'url: ' ]]; then
                url=${line#url: }

            elif [[ $line = '---' ]]; then
                # end of YAML metadata
                in_yaml=false
            fi

        elif [[ $i = 0 && $line = '---' ]]; then
            # start of YAML metadata
            in_yaml=true
        fi

        (( i = i + 1 ))
    done < $filename

    ( echo "<a href='$url'>$author - $source - $date</a>" &&
          echo "<blockquote>" &&
          breakdown $filename &&
          echo "</blockquote>" ) | xsel -b
}


if [ ! $# -eq 1 ]; then
    echo "Usage:"
    echo "  br48 FILE"
    exit 1
fi

br48 "$@"
