#!/usr/bin/env bash
#
# Dependencies:
# - breakdown
# - xsel

br48() {
    local res=
    shopt -s lastpipe  # make the last pipeline segment run in the current shell

    for filename in "$@"; do
        if [ ! -r "$filename" ]; then
            echo [ERROR] file \"$filename\" does not exist
            continue
        fi

        local i=0 in_yaml=false author date source url
        while IFS= read -r line || [ -n "$line" ]; do
            if [[ $in_yaml = true ]]; then
                if [[ $line =~ ^'author: ' ]]; then
                    author=${line#author: }
                elif [[ $line =~ ^'date: ' ]]; then
                    date=${line#date: }
                elif [[ $line =~ ^'source: ' ]]; then
                    source=${line#source: }
                elif [[ $line =~ ^'url: ' ]]; then
                    url=${line#url: }

                elif [[ $line = '---' ]]; then
                    # end of YAML metadata
                    in_yaml=false
                fi

            elif [[ $i = 0 && $line = '---' ]]; then
                # start of YAML metadata
                in_yaml=true
            fi

            (( i = i + 1 ))
        done < $filename

        local temp=
        ( echo "<strong>$author - $source - $date</strong>" &&
              # Tumblr seems to start treating posts with external links as spams
              # and stop showing them in search results (2020-04-08)
              #( echo "<a href='$url'>$author - $source - $date</a>" &&
              echo "<blockquote>" &&
              breakdown $filename &&
              echo "</blockquote>" ) | { read -r -d '' temp; res=$res$temp; }
    done

    echo $res | xsel -b
}


if [ $# -eq 0 ]; then
    echo "Usage:"
    echo "  br48 [FILES]"
    exit 1
fi

br48 "$@"
