#!/usr/bin/env bash
#
# Markdown flavor that preserves literal line breaks.
#
# Note: the end of input file should have an empty line!
#
BR_VERSION=0.1.0

br_version() {
    echo br $BR_VERSION
}

br_help() {
    br_version && echo

    echo "Usage:"
    echo "  br [FILES]"
}


if [ $# -eq 0 ]; then
    br_help
    exit 0
fi


for filename in $@; do
    if [ ! -r "$filename" ]; then
        echo [ERROR] file \"$filename\" does not exist
        continue
    fi

    while read -r line; do  # strip preceding whitespaces?
        if [[ $line =~ ^# ]]; then
            # do not append line break on headings
            echo $line
        else
            echo $line \\
        fi

    done < $filename | pandoc
done
