#!/usr/bin/env zsh
#
# Open an incognito Chromium session.

read -q "REPLY?this could mess up your last tabs if some updated extensions pop up a regular tab, you might want to ban clients2.google.com from hosts first. continue? [y/N]"
if [[ $REPLY = "n" ]]; then
    exit 1
fi
echo

chromium --incognito 2>/dev/null&
