#!/usr/bin/env zsh
#
# Save the current Chromium session.

. prelude

if [ $# -ne 1 ]; then
    echo 'Usage:'
    echo '  chrome-save NAME'
    exit 1
fi

SESSION_FILENAME="$HOME/.config/chromium/Default/Current Session"
TABS_FILENAME="$HOME/.config/chromium/Default/Current Tabs"

SESSION_SAVE_FILENAME="$HOME/.config/chromium/Default/Current Session[$1]"
TABS_SAVE_FILENAME="$HOME/.config/chromium/Default/Current Tabs[$1]"

if [[ -r "$SESSION_FILENAME" && -r "$TABS_FILENAME" ]]; then

    if [[ -r "$SESSION_SAVE_FILENAME" || -r "$TABS_SAVE_FILENAME" ]]; then
        read -q "REPLY?a session named '$1' already exists, overwrite? [y/N]"
        if [[ $REPLY = "n" ]]; then
            exit 1
        fi
        echo
    fi

    cp $SESSION_FILENAME $SESSION_SAVE_FILENAME && cp $TABS_FILENAME $TABS_SAVE_FILENAME &&
        ok 'session saved'

else
    e 'current session is not found, or it is incomplete'; exit 404
fi
