#!/usr/bin/env python
# Print the dimension of an image / media file.

import os
import re
import subprocess
import sys

def main():
    for filename in sys.argv[1:]:
        fullname = os.path.abspath(filename)
        p = subprocess.run(['file', '-b', filename], capture_output=True)
        result = p.stdout.decode('utf-8').strip()
        m = re.search(r', ((\d+)\s*x\s*(\d+))', result)
        if m is not None:
            print('%s x %s' % (m.group(2), m.group(3)))
        else:
            p = subprocess.run(['ffprobe', filename], capture_output=True)
            result = p.stderr.decode('utf-8').strip()
            m = re.search(r', ((\d+)\s*x\s*(\d+))', result)
            if m is not None:
                print('%s x %s' % (m.group(2), m.group(3)))


if __name__ == '__main__':
    main()
