#!/usr/bin/env python

# Download images from http://www.dmm.co.jp/digital/videoa/.

import json, re, sys
from you_get.common import *
from you_get.util import *

site_info = 'DMM R18'

def main():
    for arg in sys.argv[1:]:
        cont = get_content(arg)
        cid = re.findall(r'cid=([^/]+)/', cont)[0]
        print("ID:\t\t%s" % cid)
        title = re.findall(r'<title>(.*) - アダルトビデオ動画', cont)[0]
        print("Title:\t\t%s" % title)
        performers = re.findall(r'<span id="performer">[^>]*>([^<]+)</', cont)
        if performers:
            print("Performer:\t%s" % performers[0])

        cover_url = 'http://pics.dmm.co.jp/digital/video/%s/%spl.jpg' % (cid, cid)
        cover_title = '%spl' % cid
        ext, size = 'jpg', url_size(cover_url)
        download_urls(urls=[cover_url],
                      title=cover_title,
                      output_dir='.',
                      total_size=size,
                      ext=ext,
                      merge=False)

        samp_pat = 'http://pics.dmm.co.jp/digital/video/%s/%s-(\d+).jpg' % (cid, cid)
        samps = re.findall(samp_pat, cont)
        for i in samps:
            url = 'http://pics.dmm.co.jp/digital/video/%s/%sjp-%s.jpg' % (cid, cid, i)
            title = '%sjp-%s' % (cid, i)
            ext, size = 'jpg', url_size(url)
            download_urls(urls=[url],
                          title=title,
                          output_dir='.',
                          total_size=size,
                          ext=ext,
                          merge=False)

    return

if __name__ == '__main__':
    main()
