#!/usr/bin/env python

# Download all images from dwango.

import json, re, sys
from you_get.common import *
from you_get.util import *

site_info = 'dwango'

def orig(url):
    m = url.split('/')
    if m[10][0:3] in ['lg_', 'md_', 'sm_']:
        filename = m[10][3:]
        title = m[10][3:][:-4]
    else:
        filename = m[10]
        title = m[10][:-4]
    src = 'https://green-img-news-dwango-jp-prod.s3.amazonaws.com/uploads/medium/file/%s/%s' % \
        ('/'.join(m[6:10]), filename)
    return (src, title)

def main():
    for arg in sys.argv[1:]:
        download_list = []
        cont = get_content(arg)
        photos = re.findall(r'src="([^"]+)" alt="Sm ([^"]+)', cont)

        for photo in photos:
            url, title = orig(photo[0])
            ext, size = 'jpg', url_size(url)
            print_info(site_info, title, ext, size)
            download_urls(urls=[url],
                          title=title,
                          output_dir='.',
                          total_size=size,
                          ext=ext,
                          merge=False)

    return

if __name__ == '__main__':
    main()
