#!/bin/sh
#
# Show the dzen header. (for xmonad only)
#
# Dependencies:
# - dzen2

pkill -f "dzen2 -title-name header"

while true; do
    dt=`date +"%a %b %d %l:%M %p"`
    printf "^ca(1,dzcalendar)  %s  ^ca()\n" "$dt"
    sleep 20
done | dzen2 -title-name 'header' \
             -e '' -x '0' -h '18' -ta l -fn 'Ubuntu Mono'
