#!/bin/zsh

pkill -f "dzen2 -title-name quotes"

(
    # requires zsh built-in echo
    fortune $HOME/.zsh/fortune-cookies/quotes | read QUOTES
    echo -n "$QUOTES   \n"
) | dzen2 -title-name 'quotes' \
          -p -x '1000' -h '18' -ta r -fn 'Ubuntu Mono'
