#!/usr/bin/env bash

for i in "$@"; do
    T=`file -0 --mime-type "$i" | cut -d $'\0' -f2 | cut -d ' ' -f2`
    echo $T
    case $T in
        'image/gif' )
            t='gif'
            ;;
        'image/jpeg' )
            t='jpg'
            ;;
        'image/png' )
            t='png'
            ;;
        'image/x-ms-bmp' )
            t='bmp'
            ;;
        'video/mp4' )
            t='mp4'
            ;;
        * )
            t=${i##*.}
            ;;
    esac
    if [ "$t" != "${i##*.}" ]; then
        j=${i%%\?*}
        echo $i '->' ${j%.*}.$t
        mv -i "$i" "${j%.*}.$t"
    fi
done
