#!/usr/bin/env python
# Save an Instagram post in the current directory as pt format.
#
# Dependencies:
# - python ~ 3.5
#   - you-get ~ 0.4
#

import json, re, sys
from datetime import datetime
from you_get.common import *
from you_get.util import *
from you_get.extractors.instagram import instagram_download

site_info = 'Instagram'

def main():
    for url in sys.argv[1:]:
        m = re.match('https?://(www\.)?instagram\.com/.*p/([^/]+)', url) or \
            re.match('https?://(www\.)?instagram\.com/.*tv/([^/]+)', url) or \
            re.match('https?://(www\.)?instagram\.com/.*reel/([^/]+)', url)
        assert m
        title = m.group(2)
        log.w(title)

        load_cookies('/home/soimort/instagram.com_cookies.txt')
        cont = get_content(url, headers=fake_headers)

        appId = r1(r'"appId":"(\d+)"', cont)
        media_id = r1(r'"media_id":"(\d+)"', cont)

        api_url = 'https://i.instagram.com/api/v1/media/%s/info/' % media_id
        try:
            api_cont = get_content(api_url, headers={**fake_headers, **{'x-ig-app-id': appId}})
        except:
            log.wtf('[Error] Please specify a cookie file.')
        post = json.loads(api_cont)

        for item in post['items']:
            title = item['code']
            date = item['taken_at']
            post_time = datetime.fromtimestamp(date).strftime('%a %d %b %Y')
            author = item['user']['full_name']
            try:
                text = item['caption']['text']
            except:
                text = ''

            try:
                with open(title + '.pt', 'x') as outf:
                    outf.write('---\n')
                    outf.write('author: %s\n' % author)
                    outf.write('date: %s\n' % post_time)
                    outf.write('source: %s\n' % 'Instagram')
                    outf.write('url: %s\n' % url)
                    outf.write('---\n')
                    outf.write(text)
                    outf.write('\n')
            except:
                log.e("[Warning] File '%s' existed and will not be truncated." % (title + '.pt'))

        instagram_download(url)

if __name__ == '__main__':
    main()
