#!/usr/bin/env python

# Download all images from amazon.

import json, re, sys
from you_get.common import *
from you_get.util import *

site_info = 'amazon'

def main():
    for arg in sys.argv[1:]:
        # TODO: use get_content with fake headers
        response = get_response(arg, faker=False)
        page = str(response.data)

        images = re.findall(r'"hiRes":"(https://m\.media-amazon\.com/[^"]+)"', page)
        if not images:
            images = re.findall(r'"large":"(https://m\.media-amazon\.com/[^"]+)"', page)

        for image in images:
            photo_id = '.'.join(image.split('/')[-1].split('.')[:-1])
            title = '[%s] %s' % (site_info, photo_id)
            #print(title); continue #######

            ext, size = 'jpg', url_size(image)
            print_info(site_info, title, ext, size)
            download_urls(urls=[image],
                          title=title,
                          output_dir='.',
                          total_size=size,
                          ext=ext,
                          merge=False)

    return

if __name__ == '__main__':
    main()
