#!/usr/bin/env python

import json, re, sys
from you_get.common import *
from you_get.util import *

site_info = 'music-culture.info'

def main():
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0',
        'Accept-Encoding': 'gzip, deflate',
        'Accept': '*/*'
    }

    for arg in sys.argv[1:]:
        cont = get_content(arg, headers=headers)
        imgs = re.findall(r'(https://image\.jimcdn\.com/app/cms/image/transf/[^/]+/path/\w+/image/\w+/version/\d+/image\.jpg)" alt="', cont)
        imgs += re.findall(r'(https://image\.jimcdn\.com/app/cms/image/transf/[^/]+/path/\w+/image/\w+/version/\d+/image\.jpg)" data-title="', cont)
        imgs += re.findall(r'(https://image\.jimcdn\.com/app/cms/image/transf/[^/]+/path/\w+/image/\w+/version/\d+/image\.png)" alt="', cont)
        imgs = list(set(imgs))
        img_id_pool = {}
        for img in imgs:
            try:
                dimension = int(re.search(r'/dimension=(\d+)', img).group(1))
                if dimension <= 310:
                    continue
            except: pass

            ext = img.split('.')[-1]
            img_id = img.split('/')[-2]
            if img_id in img_id_pool:
                img_id_pool[img_id] += 1
            else:
                img_id_pool[img_id] = 1
            img_raw = '/'.join(img.split('/')[:7]) + '/none/' + '/'.join(img.split('/')[8:])

            title = '[music-culture.info] %s' % img_id
            if img_id_pool[img_id] > 1:
                title = '%s (%s)' % (title, img_id_pool[img_id])

            size = url_size(img_raw, headers=headers)
            print_info(site_info, title, ext, size)
            download_urls(urls=[img_raw],
                          title=title,
                          output_dir='.',
                          total_size=size,
                          ext=ext,
                          merge=False,
                          headers=headers)

    return

if __name__ == '__main__':
    main()
