#!/usr/bin/env python

# Download all images from ec.hkt48.jp.

import json, re, sys
from you_get.common import *
from you_get.util import *

site_info = 'ec.hkt48.jp'

def main():
    for arg in sys.argv[1:]:
        # TODO: use get_content with fake headers
        response = get_response(arg, faker=True)
        page = str(response.data)

        matches = re.findall(r'<div class="slide-item"><img src="([^"]+)"', page)

        for match in matches:
            image = 'https://ec.hkt48.jp%s' % match
            photo_id = image.split('/')[-1].split('.')[0]
            title = '%s' % photo_id

            ext, size = 'jpg', url_size(image)
            print_info(site_info, title, ext, size)
            download_urls(urls=[image],
                          title=title,
                          output_dir='.',
                          total_size=size,
                          ext=ext,
                          merge=False)

    return

if __name__ == '__main__':
    main()
