#!/usr/bin/env python

# Download all images from okmusic <https://okmusic.jp/>.

import json, re, sys
from you_get.common import *
from you_get.util import *

site_info = 'okmusic'

def main():
    for arg in sys.argv[1:]:
        cont = get_content(arg)
        images = re.findall(r'(https://c\.okmusic\.jp/news_details/images/\d+/original.jpg)', cont)

        i = 1
        for image in images:
            photo_id = image.split('/')[-2]
            title = '[%s] original' % photo_id

            ext, size = 'jpg', url_size(image)
            print_info(site_info, title, ext, size)
            download_urls(urls=[image],
                          title=title,
                          output_dir='.',
                          total_size=size,
                          ext=ext,
                          merge=False)

    return

if __name__ == '__main__':
    main()
