#!/usr/bin/env python

# Download all images from modelpress <https://mdpr.jp/>.

import json, re, sys
from you_get.common import *
from you_get.util import *

site_info = 'modelpress'

def main():
    for arg in sys.argv[1:]:
        download_list = []
        cont = get_content(arg)
        details = re.findall(r'a href="(/photo/detail/\d+)"', cont)
        for j in details:
            url = "https://mdpr.jp%s" % j
            download_list = []
            cont = get_content(url)
            t = re.findall(r'"(https://cdn\.mdpr\.jp/photo/images/[^"]+/(w\d+c[^"]+))"', cont)
            if not t:
                t = re.findall(r'<meta property="og:image" content="([^?]+/([^?]+))?', cont)
            for i in t:
                urls, title = [i[0]], i[1]
                ext, size = 'jpg', urls_size(urls)
                print_info(site_info, title, ext, size)
                download_urls(urls=urls,
                              title=title,
                              output_dir='.',
                              total_size=size,
                              ext=ext,
                              merge=False)

    return

if __name__ == '__main__':
    main()
