#!/usr/bin/env zsh
#
# List all saved mi-casa sessions in the HOME directory.

. prelude

# FIXME: suppress "no matches found"
if ls $HOME/*.mur 1>/dev/null 2>&1; then
    for SESSION_FILENAME in $HOME/*.mur; do
        SESSION=${SESSION_FILENAME#$HOME/}
        SESSION=${SESSION%.mur}
        if [[ -z $SESSION ]]; then
            echo '(default)'
        else
            echo $SESSION
        fi
    done
else
    e 'no saved session is found'; exit 404
fi
