#!/usr/bin/env bash
CAJA_LAST_SESSION=$HOME/.config/caja/last-session

if [ -r "$1" ]; then
    echo """<?xml version='1.0' encoding='UTF-8'?>
<session>
  <history></history>""" > $CAJA_LAST_SESSION
    echo "  <window type='navigation' geometry='1366x704+0+0' location='file://$HOME'>" >> $CAJA_LAST_SESSION

    while read -r line; do # strip preceding whitespaces
        # skip empty lines and comments
        if [[ -z $line || $line =~ ^# ]]; then
            continue
        fi

        # terminating command '***'
        if [[ $line == "***" ]]; then
            break
        fi

        # new window indicator '%'
        if [[ $line =~ ^% ]]; then
            echo "  </window>" >> $CAJA_LAST_SESSION
            echo "  <window type='navigation' geometry='1366x704+0+0' location='file://$HOME'>" >> $CAJA_LAST_SESSION
        fi

        # remove possible double quotes
        line=${line#\"}
        line=${line%\"}

        if [[ $line =~ ^sftp: ]]; then # sftp URI scheme
            true
        elif [[ $line =~ ^~ ]]; then # explicit home path, e.g., ~/Downloads
            line=$HOME${line#\~}
        elif [[ ! $line =~ ^/ ]]; then # implicit home path, e.g., Downloads
            line=$HOME/$line
        fi
        if [[ $line =~ ^sftp: ]] || [[ -d $line ]]; then
            line="${line/\#/%23}" # percent-encode '#' in path
            line="${line/\&/%26}" # percent-encode '&' in path
            if [[ $line =~ ^sftp: ]]; then # sftp URI scheme
                uri=$line
            else
                uri=file://$line
            fi
            if [[ $line =~ \' ]]; then # single quote in path
                quri="\"$uri\""
            else
                quri="'$uri'"
            fi
            echo "    <slot location=$quri/>" >> $CAJA_LAST_SESSION
        fi
    done < $1

    echo """  </window>
</session>""" >> $CAJA_LAST_SESSION
fi

gdb -ex run caja
