#!/usr/bin/env zsh
#
# A simple prelude for all scripts.

ok() {
    >&2 echo "\x1b[32;1m[INFO] "$*"\x1b[0m"
}

w() {
    >&2 echo "\x1b[33m[WARNING] "$*"\x1b[0m"
}

e() {
    >&2 echo "\x1b[33;1m[ERROR] "$*"\x1b[0m"
}

wtf() {
    >&2 echo "\x1b[31;1m[FATAL] "$*"\x1b[0m"
}
