#!/usr/bin/env python

import sys

from rembg import remove

def main():
    for arg in sys.argv[1:]:
        output_path = f'{arg}.rembg.png'
        with open(arg, 'rb') as i:
            with open(output_path, 'wb') as o:
                data = i.read()
                output = remove(data, alpha_matting=True, alpha_matting_erode_size=15)
                o.write(output)

if __name__ == '__main__':
    main()
