#!/usr/bin/env zsh
#
# List all saved SciTE sessions.

. prelude

# FIXME: suppress "no matches found"
if ls $HOME/.SciTE.session* 1>/dev/null 2>&1; then
    for SESSION_FILENAME in $HOME/.SciTE.session*; do
        SESSION=${SESSION_FILENAME#$HOME/.SciTE.session}
        if [[ -z $SESSION ]]; then
            echo '(default)'
        else
            echo $SESSION
        fi
    done
else
    e 'no saved session is found'; exit 404
fi
