#!/usr/bin/env zsh
#
# Restore a saved SciTE session.

. prelude

if [ $# -ne 1 ]; then
    echo 'Usage:'
    echo '  scite-restore NAME'
    exit 1
fi

SESSION_FILENAME="$HOME/.SciTE.session"

SESSION_SAVE_FILENAME="$HOME/.SciTE.session[$1]"

if [[ -r "$SESSION_SAVE_FILENAME" ]]; then

    if [[ -r "$SESSION_FILENAME" ]]; then
        read -q "REPLY?current session already exists, overwrite? [y/N]"
        if [[ $REPLY = "n" ]]; then
            exit 1
        fi
        echo
    fi

    cp $SESSION_SAVE_FILENAME $SESSION_FILENAME &&
        ok 'session restored'

else
    e 'session is not found, or it is incomplete'; exit 404
fi
