#!/usr/bin/env python

import fileinput
import sys
from urllib import parse

def main():
    for filename in sys.argv[1:]:
        for line in fileinput.input(filename, inplace=True):
            line = parse.unquote(line)
            sys.stdout.write(line)

if __name__ == '__main__':
    main()
