#!/usr/bin/env python
#
#

import sys, os
from urllib.parse import unquote

def main():
    for arg in sys.argv[1:]:
        uri = unquote(arg)

        os.system('wget -q --show-progress "%s"' % uri)

    return

if __name__ == '__main__':
    main()
