#!/usr/bin/env python
#
#

import sys
from urllib.parse import unquote

def main():
    for arg in sys.argv[1:]:
        uri = unquote(arg)

        print(uri)

    return

if __name__ == '__main__':
    main()
