#!/usr/bin/env bash
# Check VmSwap for used swap space of a process.

if [ -z "$1" ]; then
    echo "Usage: vmswap [PROC]"
    exit 1
fi

IDS=`pidof $1`
for i in $IDS; do
    TMP=`grep --color VmSwap /proc/$i/status | cut -f2`
    TMP=${TMP%% kB}
    TMP=`expr $TMP / 1000`
    echo $TMP MB
done
