#!/usr/bin/env python

import sys
from you_get.common import *


def orig(url):
    m = url.split('/')
    if m[10][0:3] == 'lg_':
        filename = m[10][3:]
        title = m[10][3:][:-4]
    else:
        filename = m[10]
        title = m[10][:-4]
    src = 'https://green-img-news-dwango-jp-prod.s3.amazonaws.com/uploads/medium/file/%s/%s' % \
        ('/'.join(m[6:10]), filename)
    return (src, title)

def main():
    for url in sys.argv[1:]:
        if re.match(r'https://news\.dwango\.jp/', url):
            content = get_html(url, faker=True)  # enforce UA to get all images
            tmp = re.findall(r'src="([^"]+)" alt="Sm', content)
            for url in tmp:
                src, title = orig(url)
                print(src)

        else:
            src, title = orig(url)
            print(src)

            #ext, size = 'jpg', urls_size([src])
            #download_urls(urls=[src], title=title, ext=ext, total_size=size, faker=True)


if __name__ == '__main__':
    main()
