#!/usr/bin/env python

import sys
from you_get.common import *


def main():
    for url in sys.argv[1:]:
        m = url.split('/')

        title = m[10][3:][:-4]
        src = 'https://green-img-news-dwango-jp-prod.s3.amazonaws.com/uploads/medium/file/%s/%s' % ('/'.join(m[6:10]), m[10][3:])

        ext, size = 'jpg', urls_size([src])
        download_urls(urls=[src], title=title, ext=ext, total_size=size)


if __name__ == '__main__':
    main()
