#!/bin/sh
#
# Start everything.
#
# Dependencies:
#   xmodmap, xbindkeys, xdotool
#   nautilus, chromium, scite

HOSTNAME=`hostname`

if [[ $HOSTNAME == "Babbage" ]]; then
    # workspace computer

    chromium 2>/dev/null&

    scite 2>/dev/null&

    Home

else
    # home computer

    # initialize X key bindings
    xmodmap ~/.Xmodmap
    killall -q xbindkeys; xbindkeys

    # connect to SFTP remote points using nautilus
    if [[ $HOSTNAME == "Seele" ]]; then
        nautilus sftp://soimort@hope 2>/dev/null&
    elif [[ $HOSTNAME == "Hope" ]]; then
        nautilus sftp://soimort@seele sftp://seele 2>/dev/null&
    fi
    sleep 2  # wait a short while until it's done

    scite 2>/dev/null&

    Home
fi
