#!/usr/bin/env zsh
#
# Start everything I need.
#
# Dependencies:
# - sshfs
# - xmodmap, xbindkeys, xdotool
# - nautilus, scite
# - tmux, htop, mi-casa/caja

set -x
. prelude

#HOST=`hostname`

welcome_init() {
    if [[ $HOST == "Ada" ]]; then

        # mount SSHFS locally
        sshfs soimort@Hope:/ /mnt/Hope
        sshfs soimort@Seele:/ /mnt/Seele

    elif [[ $HOST == "Hope" ]]; then

        # initialize X key bindings
        xmodmap ~/.Xmodmap
        killall -q xbindkeys; xbindkeys

        # start devilspie2
        killall -q devilspie2; devilspie2&

        # mount SSHFS locally
        sshfs soimort@Ada:/ /mnt/Ada
        sshfs soimort@Seele:/ /mnt/Seele

        # TBD: obsolete this in favor of SSHFS
        # connect to SFTP remote points using nautilus
        nautilus sftp://soimort@seele sftp://seele 2>/dev/null&
        sleep 2  # wait a short while until it's done

    elif [[ $HOST == "Seele" ]]; then

        # initialize X key bindings
        xmodmap ~/.Xmodmap
        killall -q xbindkeys; xbindkeys

        # connect to SFTP remote points using nautilus
        nautilus sftp://soimort@hope 2>/dev/null&
        sleep 2  # wait a short while until it's done

    fi
}

welcome_start() {
    scite 2>/dev/null&
}

# Start the default monitored file management session.
welcome_home() {
    tmux new-session -d 'htop'
    # if something goes wrong, show error message forever
    tmux split-window -l 1 -v "setsid mi-casa $HOME/_ || sleep infinity"
    tmux -2 attach-session -d
}


local SUBCOMMAND=$1
case $SUBCOMMAND in
    '--init' | 'init' )
        welcome_init
        ;;

    '--start' | 'start' )
        welcome_start
        ;;

    '--home' | 'home' )
        welcome_home
        ;;

    '')
        welcome_init
        welcome_start
        welcome_home
        ;;

    * )
        e "invalid subcommand '$1'."
        exit 1
        ;;
esac
